# Gathering a corpus. Resolving roots into a set of paths, and parsing each path once
# into the `ParsedFile` records every later pass reads. What runs over those records
# lives in `analyze.jl`.

# Text a generated or bundled file announces itself with: a bundler's module runtime, or a
# generator's header line. Plain substrings rather than a tree-sitter query, the one place
# Dendro reads a file as text. The bargain governs what it measures; this decides what it
# reads at all, the question `ignore.jl` answers over a path. AGENTS.md carries what a
# bundle left in the corpus costs.
const GENERATED_SIGNATURES = [
    "__webpack_require__", "parcelRequire", "__toESM(",
    "<auto-generated", "Generated by", "@generated", "DO NOT EDIT",
]

# How far into a file a signature counts, in lines.
#
# Measured over 18279 source files in 24 corpora: typescript-sdk, julia-vscode, quarto-cli,
# mermaid, lodash, graphology, express, vscode-js-debug, renovate, windows-rs, tree-sitter,
# tree-sitter-julia, rails, redis, serde, and the nine the bands are measured over. Forty-nine
# files carry a signature somewhere. Twenty-nine of those are generated or bundled, and
# twenty are hand-written source that names one.
#
#     window        caught   false positives
#     5                  9                 0
#     10                17                 0
#     20                19                 2
#     40                21                 2
#     whole file        29                20
#
# A generated file announces itself at the top, where a header goes: 17 of the 29 land by
# line 10 and only four more by line 40. A false positive can sit on any line, so widening
# the window buys them at a steady rate long after it has stopped buying anything else.
# Whole-file matching is where that ends, at 20 hand-written files turned away.
#
# Forty rather than ten for what the band from 11 to 40 holds: pdf.js's viewer.js at 652 KB,
# a Vue vendor chunk at 357 KB, two lodash bundles. Those are the files that flood a
# baseline. The two false positives it costs are Rails source of 2 KB each whose instance
# variables begin `@generated`, and the scan names both in its warning and its report line.
# `@generated` is the weakest of the signatures and the measurement says so: it accounts for
# 12 of the 20 false positives whole-file matching would take.
const GENERATED_HEAD_LINES = 40

# How many paths the one warning per scan names before it stops listing them.
const GENERATED_WARN_PATHS = 5

"""
    generated_signatures(config) -> Vector{String}

The signatures a scan matches each file's head against: the built-in
`GENERATED_SIGNATURES` plus whatever `config` adds, or none when it turned the filter off.
Resolved in one place, so every route into a parse reads the same list.
"""
generated_signatures(config::Config) =
    config.generated_enabled ? String[GENERATED_SIGNATURES; config.generated] : String[]

# The first `n` lines of a source, the region a signature has to appear in. Matching the
# whole file would turn away a file that merely discusses a bundler, where a header is what
# a generator writes. A file shorter than `n` lines is its own head, and so is a minified
# bundle written on one line.
function head_lines(source::String, n::Int)::SubString{String}
    stop = firstindex(source)
    for _ in 1:n
        nl = findnext('\n', source, stop)
        nl === nothing && return SubString(source)
        stop = nextind(source, nl)
    end
    return SubString(source, firstindex(source), prevind(source, stop))
end

# The signature naming `source` as generated, or `nothing` when its head carries none. An
# empty list is the filter turned off, and costs a scan the lookup and nothing more.
function generated_signature(source::String, signatures::Vector{String})
    isempty(signatures) && return nothing
    head = head_lines(source, GENERATED_HEAD_LINES)
    for sig in signatures
        occursin(sig, head) && return sig
    end
    return nothing
end

# One warning for the whole scan, naming the count and the first few paths with what named
# each. Per file it would bury a report under a vendored tree of a hundred bundles; silent,
# it would leave a reader unable to tell an empty report from a corpus that lost half its
# files.
function warn_generated(excluded::Vector{GeneratedFile})
    isempty(excluded) && return nothing
    shown = String[string(g.path, " (", g.signature, ")") for g in first(excluded, GENERATED_WARN_PATHS)]
    @warn "Dendro: skipping file(s) whose head names them as generated" count = length(excluded) files = shown
    return nothing
end

"""
    ParseOptions

What a parse pass does beyond building each file's query index: the active `rules` a
directive is validated against, the `patterns` to index and the `pattern_dirs` to read
their queries from, whether to resolve `bindings`, whether to read inline `directives`, and
the `generated` signatures a file's head is turned away for (empty to parse every file).

A reference corpus (a [`Library`](@ref)) is read and never scored, so it needs none of the
optional walks: no rule runs over it, nothing asks what it binds, and no directive in it
suppresses anything. Over a large dependency set the binding resolution alone is the
difference between usable and not. The options travel in one value rather than as more
parameters on [`parse_chunk!`](@ref), the same way scan state travels in a `Scan`.
"""
struct ParseOptions
    rules::Vector{Rule}
    patterns::Vector{PatternSpec}
    pattern_dirs::Vector{String}
    bindings::Bool
    directives::Bool
    generated::Vector{String}
end

ParseOptions(;
    rules = BUILTIN_RULES, patterns::Vector{PatternSpec} = PatternSpec[],
    pattern_dirs::Vector{String} = String[], bindings::Bool = true, directives::Bool = true,
    generated::Vector{String} = GENERATED_SIGNATURES
) = ParseOptions(convert(Vector{Rule}, rules), patterns, pattern_dirs, bindings, directives, generated)

# Parse each path once. Each record carries everything the baseline, the per-file
# scoring pass, and duplicate clustering need, so no file is parsed twice. Files
# whose language has no profile are skipped. `language` forces one language for
# every path, as `analyze` does. `bindings` and `directives` turn off the optional walks
# for a corpus that is read and never scored. `generated` is the signature list a file's
# head is turned away for, and `excluded` is the sink a caller passes to read back which
# files were: a report line names them, where the diagram and reference-index routes only
# need them gone.
function parse_corpus(
        paths::AbstractVector{<:AbstractString}; language = nothing,
        rules = BUILTIN_RULES, profiles::Dict{Symbol, LanguageProfile} = PROFILES,
        patterns::Vector{PatternSpec} = PatternSpec[], pattern_dirs::Vector{String} = String[],
        bindings::Bool = true, directives::Bool = true,
        generated::Vector{String} = GENERATED_SIGNATURES,
        excluded::Vector{GeneratedFile} = GeneratedFile[]
    )
    forced = language === nothing ? nothing : Symbol(lowercase(String(language)))
    extensions = extension_map(profiles)
    entries = Tuple{String, LanguageProfile}[]
    for path in paths
        lang = forced === nothing ? language_for_path(path, extensions) : forced
        lang === nothing && continue
        haskey(profiles, lang) || continue
        push!(entries, (String(path), profiles[lang]))
    end
    n = length(entries)
    files = Vector{ParsedFile}(undef, n)
    # Warm every language's caches up front, so no parse task pays a grammar load or a
    # query compile mid fan-out; this also leaves the imports query warm for the linkage
    # passes.
    langs = unique(last(e) for e in entries)
    warm_languages(langs)
    # Compile every pattern query before the fan-out too. A malformed one is a ConfigError
    # the caller should see once, not once per parse task racing to report it.
    isempty(patterns) || foreach(p -> pattern_queries(p, pattern_dirs, patterns), langs)
    options = ParseOptions(; rules, patterns, pattern_dirs, bindings, directives, generated)
    # Written at each entry's own index like `files`, so the fan-out needs no lock and the
    # report reads the exclusions in corpus order.
    signatures = Vector{String}(undef, n)
    parallel_chunks(() -> Dict{LanguageProfile, TreeSitter.Parser}(), n) do parsers, idxs
        parse_chunk!(files, signatures, parsers, entries, idxs, options)
    end
    for i in 1:n
        isassigned(signatures, i) && push!(excluded, GeneratedFile(first(entries[i]), signatures[i]))
    end
    warn_generated(excluded)
    # A file the parse boundary turned away leaves its slot unassigned. Compacting in index
    # order keeps the corpus order every later pass and the parallel determinism rely on.
    return ParsedFile[files[i] for i in 1:n if isassigned(files, i)]
end

# Parse one chunk of files with the chunk's parser pool: a `TreeSitter.Parser` is stateful,
# so each chunk keeps its own, reused across its files. Writes into the shared preallocated
# `files` at each entry's index, so the corpus order matches the serial path. A file the
# parser cannot take leaves its slot unassigned and `parse_corpus` drops it; one its head
# names as generated leaves that slot unassigned too and writes the matching signature into
# `signatures` instead, which is what the scan reports.
function parse_chunk!(
        files::Vector{ParsedFile}, signatures::Vector{String},
        parsers::Dict{LanguageProfile, TreeSitter.Parser},
        entries::Vector{Tuple{String, LanguageProfile}}, idxs, options::ParseOptions
    )
    for i in idxs
        path, profile = entries[i]
        source = read(path, String)
        # A generated file is not the author's code, and a bundle of it is not even code a
        # reader has. Both leave the corpus before parsing, for the reason an ignored path
        # does: they would be measured, ranked, and clustered as though someone wrote them.
        sig = generated_signature(source, options.generated)
        if sig !== nothing
            signatures[i] = sig
            continue
        end
        # Tree-sitter takes the source as a C string, so a byte no C string can carry is a
        # file the parser will never accept. A corpus holds such a file now and then, a
        # fuzzer test case checked in beside real source, and one of them must not take the
        # whole scan down. Report it and carry on, the honest-over-silent reading: naming the
        # file is what tells a skipped file from a clean one.
        if occursin('\0', source)
            @warn "Dendro: skipping a file with an embedded NUL byte, which cannot be parsed" path
            continue
        end
        parser = get!(() -> parser_for(profile), parsers, profile)
        tree = parse_source(parser, source)
        index = build_index(
            tree, profile.name, source, query_for(profile), scopes_query_for(profile);
            bindings = options.bindings
        )
        # Skipped entirely for a project that declares no rules, so the second query family
        # costs an unconfigured scan nothing at all.
        isempty(options.patterns) ||
            index_all_patterns!(index, tree, pattern_queries(profile, options.pattern_dirs, options.patterns), source)
        directives = options.directives ?
            suppressions(index; file = path, rules = options.rules) : Directive[]
        files[i] = ParsedFile(profile, source, path, tree, index, directives)
    end
    return nothing
end

# Recurse a directory for files Dendro can analyze, pruning dot-directories like
# `.git` and keeping only files whose extension resolves to a language profile.
# `ignore` patterns, matched against each path relative to `dir`, prune directories
# and drop files before they reach the corpus, so vendored source never feeds the
# baseline.
function source_files(
        dir::AbstractString, ignore = String[];
        profiles::Dict{Symbol, LanguageProfile} = PROFILES
    )
    patterns = compile_ignores(ignore)
    extensions = extension_map(profiles)
    files = String[]
    for (root, dirs, names) in walkdir(dir)
        filter!(dirs) do d
            !startswith(d, ".") && !is_ignored(patterns, relpath(joinpath(root, d), dir), true)
        end
        for name in names
            lang = language_for_path(name, extensions)
            (lang === nothing || !haskey(profiles, lang)) && continue
            is_ignored(patterns, relpath(joinpath(root, name), dir), false) && continue
            push!(files, joinpath(root, name))
        end
    end
    return files
end

# Resolve a list of roots into the unique set of file paths to parse. A directory is
# walked for analyzable source under `ignore`; a named file is taken as-is, but only
# when its language can be inferred or `language` forces one. The shared front of
# `analyze` and `mermaid`, so both see the same corpus from the same roots.
function collect_corpus(
        roots::Vector{String}, ignore, language;
        profiles::Dict{Symbol, LanguageProfile} = PROFILES
    )
    isempty(roots) && error("Dendro: no paths given")
    extensions = extension_map(profiles)
    corpus = String[]
    for path in roots
        ispath(path) || error("Dendro: no such path $path")
        if isdir(path)
            append!(corpus, source_files(path, ignore; profiles))
        else
            language === nothing && language_for_path(path, extensions) === nothing &&
                error("Dendro: cannot infer language for $path; pass `language=`.")
            push!(corpus, path)
        end
    end
    unique!(corpus)
    return corpus
end
